prerelease: true

# Filter previous releases considering target_commitish
include-pre-releases: true
filter-by-commitish: true

# Versioning configuration
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'BREAKING CHANGES'
    labels:
      - 'breaking'
  - title: '💎 Features'
    labels:
      - 'feature'
  - title: '🚀 Improvement'
    labels:
      - 'improvement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'support'
      - 'dependencies'

category-template: '### $TITLE'

change-title-escapes: '\<*_&#@`'  # Updated to disable mentions and code blocks

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

autolabeler:
  - label: 'feature'
    branch:
      - '/^feat\/.+/'
  - label: 'improvement'
    branch:
      - '/^imprv\/.+/'
  - label: 'bug'
    branch:
      - '/^fix\/.+/'
    title:
      - '/^fix/i'
  - label: 'support'
    branch:
      - '/^support\/.+/'
    title:
      - '/^support/i'
      - '/^chore/i'
      - '/^ci/i'
      - '/^docs/i'
      - '/^test/i'

include-labels:
  - breaking
  - feature
  - improvement
  - bug
  - support
  - dependencies

exclude-labels:
  - 'exclude-from-changelog'

template: |
  $CHANGES

  **Full Changelog**: https://github.com/andtopic/andtopic/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION