name: Add Issue to Project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.6.1
        with:
          project-url: https://github.com/orgs/andtopic/projects/1
          github-token: ${{ secrets.ISSUE_TO_PROJECT_TOKEN }}
          labeled: feature, chore, bug
          label-operator: OR
